### ISSUE TITLE
No module named 'load_corrupted_data_mlg'

### ISSUE THREAD

**Issue by XPandora** [microsoft/MLC#1]
Hi,

Thanks for your great work! When I tried to run the code on CIFAR-10 with the command provided, I found the module 'load_corrupted_data_mlg' is missing. Did you miss this file or should I install other libraries?

**Comment by apsyx** [comment]
Thanks for pointing this out! Yes, the file was left our in previous push. It's fixed now and please report additional errors if you encounter any.

**Comment by XPandora** [comment]
Thanks a lot! It works now.
