### ISSUE TITLE
missing wideresnet and utils file

### ISSUE THREAD

**Issue by justlovebarbecue** [microsoft/MLC#2]
Hi Guoqing,

Thanks for sharing the code! I am trying to run your code and find that in the cifar dataset file, the "utils" file is missed. And I found it in the clothing dataset file. 

In addition, it seems like the "wideresnet" imported in "load_corrupted_data_mlg" is also missed, I didn't find it in other files.
Could you please tell me where to find it or did I miss anything?

Thx

**Comment by apsyx** [comment]
Hi,

Thanks for reporting the issue! I pushed the utils for CIFAR (It's left out in previous push). Also, the dependency on wideresnet is removed (we tried it in pilot studies but it's not used in the paper).

Please report any additional errors you encountered.
