### ISSUE TITLE
Approxiamation for K steps

### ISSUE THREAD

**Issue by OutstanderWang** [microsoft/MLC#3]
This work propose to approximate the current meta-parameter gradient with information from the previous k step as follows:
![image](https://user-images.githubusercontent.com/7700200/115366969-554cf400-a1f8-11eb-8782-dab3517344cb.png)
I guess the second term is the gradient of alpha for just one step, but I haven't seen why the first term can approximate the previous K.
In the code, author seems to calculate the above equ 4 every iteration, and accumulate the gradients and update meta parameter every K step.

    # accumulate discounted iterative gradient
    for i, param in enumerate(meta_net.parameters()):
        if param.grad is not None:
            param.grad.add_(gamma * args.dw_prev[i])
            args.dw_prev[i] = param.grad.clone()
    if (args.steps+1) % (args.gradient_steps)==0: # T steps proceeded by main_net
        meta_opt.step()
        args.dw_prev = [0 for param in meta_net.parameters()] # 0 to reset 

Could you please help further explain the gamma and how the equ 4 can approximate the K step gradients? Thanks @apsyx

**Comment by apsyx** [comment]
Hi,

Thanks for your detailed interest in the MLC framework. Specifically regarding the formula, you are right that the second term is computing the gradient for alpha for one step. The first term is dealing with the steps prior to the last one. I assume the formula is taken from the conference preprint, you can check a slightly more detailed derivation of the formula from the camera ready version [here](https://www.microsoft.com/en-us/research/uploads/prod/2020/12/mlc_aaai21_zheng_camera.pdf) (Eq 4-6).

In sum, to compute the meta-gradient with multiple steps, the trick to implement in practice is to reuse the meta-gradient computed with **all steps up until the previous one** and use that to approximate the meta-gradient with **all steps up until the current step**.  The condition to check if args.steps is a multiple of k is essentially to truncate to just k-steps at most (i.e., resetting args.dw_prev and re-accumulate from there). The last three lines of code in the snippet is essentially doing this. 

This reduces the need to cache multiple copies of model gradients, but at the same time this neat approximation comes at a cost: the more steps we use the larger the error will accumulate.

Hope this helps and happy to clarify more.

**Comment by OutstanderWang** [comment]
Hi @apsyx , thank you for the reply!
It is a good idea to accumulate the historical gradients to save the memory in a moving average style. But I still have some questions about how equ 5 is estimated by equ 6.
![image](https://user-images.githubusercontent.com/7700200/116024884-c6215f80-a681-11eb-9ca5-fbbe8dbd4a44.png)

In Equ 5 there is H_{w,w}, I am wondering where the g_{w^T}/||g_w||^2 comes from if estimating H_{w,w} as the identity ?

**Comment by apsyx** [comment]
Hi, besides approximating H_{w,w} with identity, the following approximation is also used to make it possible to just iterate on previous meta-gradient to get the current meta-gradient (From (5) to (6)): 

<img src="https://latex.codecogs.com/svg.image?\frac{\partial&space;w}{\partial\alpha}=I\frac{\partial&space;w}{\partial\alpha}\approx\frac{g_w^\top}{\|g_w\|^2}g_w\frac{\partial&space;w}{\partial\alpha}=\frac{g_w^\top}{\|g_w\|^2}\frac{\partial\mathcal{L}_D(w)}{\partial\alpha}"/>

where <img src="https://latex.codecogs.com/svg.image?\inline\frac{g_w^\top&space;g_w}{\|g_w\|^2}"/> is used to approximate identity (Note in the formula g_w is a row vector not a column vector). This is a crude approximation, but allows us to iterate directly over the meta-gradients as in (6)

**Comment by OutstanderWang** [comment]
Got it, Thanks a lot for your reply!
