### ISSUE TITLE
No such file or directory: 'data/clothing1M/clean_train'

### ISSUE THREAD

**Issue by ghost** [microsoft/MLC#4]
Hi, dear author.

Thank you for your excellent work!

But when I try to run your code in clothing1M dataset (I follow the instruction in readme), but directory "clean_train" does not exist. Could you provide the related code about this directory?

Thank you very much.

**Comment by apsyx** [comment]
Hello,

Thank you for your interest in our work. The folder data/clothing1M is for placing the clothing1M data. As we described in README, for Clothing1M, as we do not own the Clothing1M data set we cannot share the data in this repo, please contact the [original creator](https://github.com/Cysu/noisy_label) for data access.

Hope this helps.

**Comment by apsyx** [comment]
If you already obtained the data, there is indeed some simple processing to prepare the clean_train, clean_val, noisy_train, clean_test folders. I just uploaded a script `load_cloth1m_data.py` under CLOTHING1M, please run `python3 load_cloth1m_data.py` under the CLOTHING1M directory and it'll generate all four folders.

**Comment by ghost** [comment]
Thank you very much!
It is worked!
