### ISSUE TITLE
The default value of gradient_steps 

### ISSUE THREAD

**Issue by zhangmeishan** [microsoft/MLC#5]
The default  value of gradient_steps is set to 1 (main.py), which seems that the first term of the eqn 6 in your paper is never used.

if (args.steps + 1) % (args.gradient_steps) == 0:  # T steps proceeded by main_net
        meta_opt.step()
        args.dw_prev = [0 for param in meta_net.parameters()]  # 0 to reset

The condition in the if expression is always True.

**Comment by apsyx** [comment]
Hi, thank you for your interest in our work. You are right that K (number of gradient_steps) is default to 1 in the code. You can pass different values to the example command --gradient_steps K.

The first term in Eq (6) will be non-zero only if K>1. We tested different K with 1, 5, 10 for experiments in the paper and you can find analysis on K in Figure 5.
