### ISSUE TITLE
Problems about the approximated gradient of validation loss w.r.t. the meta model

### ISSUE THREAD

**Issue by guangliang-nlp** [microsoft/MLC#7]
Hi, I have tried to prove equation 4  several times, but I cannot figure out why there is a subtraction in equation 4. I have proved the approximated gradient of meta model from the [Meta-Weight-Net](https://arxiv.org/abs/1902.07379).  I think the method to get the implicit gradient of validation loss w.r.t. meta model is similar. Can you please share the detailed proof regarding how to get the equation 4-6? thanks.

**Comment by guangliang-nlp** [comment]
I  checked out the issue #3 but I still can not figure out how to get the first term of equation 4. It would be great if the author can share more details. Thanks.

**Comment by randydkx** [comment]
@guangliang-nlp Note that Meta-Weight-Net is just one-step ahead, that's to say, w is independent of alpha, but in this paper, w is dependent on alpha. You can check it from the Figure 3 where MWN belongs to the  pic in left corner, all the previous w_k except w_0 depends on alpha_0. So w' = w(alpha) - eta - d_wLD'(alpha,w(alpha)).Then using the chain rule and the dependence graph(Fig 3), you can easy get the Eq 4.

**Comment by apsyx** [comment]
Note that in the one-step update, w'=w-lambda * g(w), if you consider the formulation of MLC, both w and g(w) will be functions of meta parameters alpha. By applying chain-rule, you can get the first term.

Also thanks @randydkx for helping clarify!
